### ISSUE TITLE
Заменить "hard coded" контактные данные на компонент

### ISSUE THREAD

**Issue by mrhyde** [FAS/fasenergo.ru#45]
На странице с информацией о доставке указан номер телефона ДКТ (т.е. подменный и нам не принадлежащий), просьба заменить на этой и других страницах которые вы редактировали контактные данные на компонент который выводит их из data файла.
Пример на странице контактов:
https://github.com/FAS/fasenergo.ru/blob/master/source/templates/контакты/index.nj

**Comment by mrhyde** [comment]
@LowRideSky

**Comment by LowRideSky** [comment]
Где-то еще исправлялись контакты?
Не могу найти свои коммиты в master

**Comment by mrhyde** [comment]
Посколько username на github'e не совпадает с автором коммитов поиск по истории невозможен из интерфейса github
Я проверил, на остальных страницах использовался блок с формой и CTA по этому контактов там нет.

Спасибо
